PublicBodyCategories.add(:pt, [
    "Esfera",
        [ "federal", "No Brasil", "Órgãos da esfera federal" ],
        [ "estadual", "No seu estado", "Órgãos da esfera estadual" ],
        [ "municipal", "Na sua cidade", "Órgãos da esfera municipal" ],
    "Poder",
        [ "executivo", "Executivo", "Órgãos do poder executivo – executam as políticas (ex: prefeituras, governos, secretarias, ministérios)"],
        [ "legislativo", "Legislativo", "Órgãos do poder legislativo – fazem leis e fiscalizam o executivo (ex: câmaras, assembleias legislativas, Senado, Câmara dos Deputados, Tribunais de Contas)"],
        [ "judiciario", "Judiciário", "Órgãos do poder judiciário – julgam casos e aplicam as leis (ex: fóruns, tribunais de justiça, Supremo Tribunal Federal, tribunais eleitorais) "],      
    "Área de Atuação",
        [ "saude", "Saúde", "Órgãos que trabalham com saúde (ex: dados de hospitais públicos, SUS, medicamentos, profissionais de saúde)" ],
        [ "educacao", "Educação", "Órgãos que trabalham com educação (ex: listas de escolas públicas, dados de diretorias de ensino, informações de universidades públicas)" ],
        [ "cultura", "Cultura", "Órgãos que trabalham com cultura (ex: informações sobre espaços de arte e música, listas de pontos de cultura, programação cultural de eventos públicos)"] ,
        [ "direitoshumanos", "Direitos Humanos", "Órgãos que trabalham com direitos humanos (ex: dados gerais sobre direitos da mulher, direitos da criança e do adolescente, direitos do idoso, racismo, tortura)"],
        [ "comunicacao", "Comunicação", "Órgãos que trabalham com comunicação (ex: informações sobre concessões de TVs públicas e rádios comunitárias, planos de internet banda larga, regras para telefonia celular)"],
        [ "transporte", "Transporte", "Órgãos que trabalham com transporte (ex: dados de onde há transporte público; horários e rotas de ônibus, informações sobre rodovias)"],
        [ "moradia", "Moradia", "Órgãos que trabalham com moradia (ex: informações sobre programas de habitação, Minha Casa, Minha Vida, CDHU, Morar Melhor, regras de financiamento Caixa)" ],
        ["trabalho", "Trabalho", "Órgãos que trabalham com trabalho (ex: dados sobre desemprego, direitos trabalhistas"],
        ["economia", "Economia", "Órgãos que trabalham com economia (ex: índices de inflação, histórico da taxa de crescimento, PIB, cotação do dólar)"],
        ["gastospublicos", "Gastos Públicos", "Órgãos que trabalham com gastos públicos (ex: dados de finanças públicas, orçamentos, despesas, impostos)"],    
    "Tipos comuns",
        ["presidencia", "Presidência", "Presidência - governo do país"],
        [ "ministerio", "Ministérios", "Ministérios"],
        [ "governo", "Governos Estaduais", "Governos Estaduais - governos dos estados"],
        [ "prefeitura", "Prefeituras", "Prefeituras - governos das cidades"],
        [ "secretaria", "Secretarias", "Secretarias"],
    "Outros",
        [ "outros", "Outros", "Outros"]
])

